# Version of docker-compose
version: '3'

services:
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
      SERVICE_PORTS: 5432
    restart: always
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web
  # Our Phoenix container
  phoenix:
    image: phoenix:v1
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: football_results_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
      SERVICE_PORTS: 4000
      # VIRTUAL_HOST: "/api/*"
    ports:
      - "4000"
    networks:
      - web
    depends_on:
      # The db container needs to be started before we start this container
      - db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
  # HAProxy setup
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - web
      - db
      - phoenix
    environment:
      - BALANCE=leastconn
      - ADDITIONAL_SERVICES=project_dir:phoenix,project_dir:db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

# Define the volumes
volumes:
  pgdata:

# Define the networks
networks:
  web:
    driver: overlay
